// DARK MODE
export const DARK_MODE_SUCCESS = 'DARK_MODE_SUCCESS';
export const DARK_MODE_FAIL = 'DARK_MODE_FAIL';
export const GET_DARK_MODE = 'GET_DARK_MODE';

// USER
export const USER_SIGNUP_SUCCESS = 'USER_SIGNUP_SUCCESS';
export const USER_LOGIN_REQUEST = 'USER_LOGIN_REQUEST';
export const USER_LOGIN_SUCCESS = 'USER_LOGIN_SUCCESS';
export const USER_LOGIN_FAIL = 'USER_LOGIN_FAIL';
export const USER_LOGOUT_SUCCESS = 'USER_LOGOUT_SUCCESS';
export const USER_PROFILE_SUCCESS = 'USER_PROFILE_SUCCESS';
export const USER_PICTURE_UPDATE_SUCCESS = 'USER_PICTURE_UPDATE_SUCCESS';


// selected mode
export const SELECTED_MODE = 'SELECTED_MODE';

// grid mode
export const GRID_MODE_SUCCESS = 'GRID_MODE_SUCCESS';

// notes action
export const GET_NOTES_REQUEST = 'GET_NOTES_REQUEST';
export const GET_NOTES_SUCCESS = 'GET_NOTES_SUCCESS';
export const GET_NOTES_FAIL = 'GET_NOTES_FAIL';
export const NOTES_UPDATE_SUCCESS = 'NOTES_UPDATE_SUCCESS';
export const NOTES_DELETE_SUCCESS = 'NOTES_DELETE_SUCCESS';
export const NOTES_CREATE_SUCCESS = 'NOTES_CREATE_SUCCESS';
export const PINNED_NOTES_SUCCESS = 'PINNED_NOTES_SUCCESS';
export const NOTES_SEARCH_SUCCESS = 'NOTES_SEARCH_SUCCESS';

// todo action
export const GET_TODOS_REQUEST = 'GET_TODOS_REQUEST';
export const GET_TODOS_SUCCESS = 'GET_TODOS_SUCCESS';
export const GET_TODOS_FAIL = 'GET_TODOS_FAIL';
export const TODO_UPDATE_SUCCESS = 'TODO_UPDATE_SUCCESS';
export const TODO_DELETE_SUCCESS = 'TODO_DELETE_SUCCESS';
export const TODO_CREATE_SUCCESS = 'TODO_CREATE_SUCCESS';
export const TODO_COMPLETE_SUCCESS = 'TODO_COMPLETE_SUCCESS';
export const TODO_HIDE_SUCCESS = 'TODO_HIDE_SUCCESS';